### ISSUE TITLE
Problem with edit_event route.

### ISSUE THREAD

**Issue by ishancoder** [razat249/ecb-sac-final-app#1]
While visiting the route of `localhost:3000/#/edit_event` the edit page appears. But when i logged out. the page is not redirect to `localhost:3000/#/home`

**Comment by razat249** [comment]
Yup there is a redirect problem

**Comment by ishancoder** [comment]
#Solved
The problem was that the edit-event.js file was hard coded with the link of an event.
I have changed it to dynamically load event's id when it got saved.
